development: &default
  adapter: postgresql
  database: counting-game_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost

test:
  <<: *default
  database: counting-game_test
